services:
  - type: web
    name: ai-website-analyzer
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install  # For JS-rendering with Playwright
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
