services:
  - type: web
    name: my-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: streamlit run app.py --server.port $PORT
    plan: free
